# Generated by Django 4.0.5 on 2022-06-29 22:52

import catalogos.models
import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'cursos_alumnos',
            },
        ),
        migrations.CreateModel(
            name='AlumnoSelfRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('phone', models.CharField(max_length=200, verbose_name='Telefono')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'cursos_alumnos_self',
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'cursos_categorias',
            },
        ),
        migrations.CreateModel(
            name='CursoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion')),
                ('fechayhora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio')),
                ('fechayhora_final', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de finalizacion')),
                ('duracion_hrs', models.IntegerField(blank=True, null=True, verbose_name='Duracion en Horas')),
                ('lugar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar')),
                ('registros_abiertos', models.BooleanField(default=True, verbose_name='Registros Abiertos')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Curso Evento',
                'verbose_name_plural': 'Cursos Evento',
                'db_table': 'curso_evento',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('rfc', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('state', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('country', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('cp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cursos_empresas',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=200, verbose_name='Apellido')),
                ('telefono', models.CharField(max_length=200, verbose_name='Telefono')),
                ('email', models.CharField(max_length=200, verbose_name='e-Mail')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=catalogos.models.get_image, validators=[core.validators.validate_file_extension], verbose_name='Imagen')),
                ('rfc', models.CharField(blank=True, max_length=14, null=True, verbose_name='RFC')),
                ('banco', models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco')),
                ('cuentabancaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta Bancaria')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructores',
                'db_table': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='RegistroEventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechayhora', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de inicio')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('pagado', models.BooleanField(default=True, verbose_name='status')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.alumnos', verbose_name='Alumno')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.cursoevento', verbose_name='Curso Evento')),
            ],
            options={
                'verbose_name': 'Registro Evento',
                'verbose_name_plural': 'Registros Eventos',
                'db_table': 'cursos_regitroeventos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('description', models.CharField(blank=True, max_length=800, null=True, verbose_name='Descripcion')),
                ('description2', models.CharField(blank=True, max_length=800, null=True, verbose_name='Descripcion 2')),
                ('description3', models.CharField(blank=True, max_length=800, null=True, verbose_name='Descripcion 3')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.categorias', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'cursos',
            },
        ),
        migrations.AddField(
            model_name='cursoevento',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Curso_Evento', to='catalogos.cursos', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='cursoevento',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='alumnos',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.empresa', verbose_name='Empresa'),
        ),
    ]
