# Generated by Django 4.0.5 on 2022-06-30 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registroeventos',
            table='cursos_registroeventos',
        ),
    ]
