# Generated by Django 4.0.5 on 2022-07-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_alter_registroeventos_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroeventos',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='registroeventos',
            name='evento',
        ),
        migrations.DeleteModel(
            name='CursoEvento',
        ),
        migrations.DeleteModel(
            name='RegistroEventos',
        ),
    ]
