# Generated by Django 4.0.2 on 2022-07-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_remove_registroeventos_alumno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sedes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la sede')),
                ('domicilio', models.CharField(max_length=50, verbose_name='Domicilio')),
                ('Estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('Ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('cp', models.CharField(max_length=50, verbose_name='Codigo postal')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('rfc', models.CharField(max_length=50, verbose_name='RFC')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('cuentabancaria', models.CharField(max_length=50, verbose_name='Cuenta Bancaria')),
                ('nombrecontacto', models.CharField(max_length=50, verbose_name='Nombre contacto')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'cursos_sedes',
            },
        ),
    ]
