# Generated by Django 4.0.5 on 2022-07-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0004_sedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedes',
            name='capacidad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='sedes',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='Ciudad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='Estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='banco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='cp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codigo postal'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='cuentabancaria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuenta Bancaria'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='domicilio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='nombrecontacto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre contacto'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='rfc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RFC'),
        ),
        migrations.AlterField(
            model_name='sedes',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
